/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WagersIndexRouteImport } from './routes/wagers/index'
import { Route as WagersNewRouteImport } from './routes/wagers/new'
import { Route as WagersWagerIdRouteImport } from './routes/wagers/$wagerId'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WagersIndexRoute = WagersIndexRouteImport.update({
  id: '/wagers/',
  path: '/wagers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WagersNewRoute = WagersNewRouteImport.update({
  id: '/wagers/new',
  path: '/wagers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WagersWagerIdRoute = WagersWagerIdRouteImport.update({
  id: '/wagers/$wagerId',
  path: '/wagers/$wagerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/terminal': typeof TerminalRoute
  '/wagers/$wagerId': typeof WagersWagerIdRoute
  '/wagers/new': typeof WagersNewRoute
  '/wagers/': typeof WagersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/terminal': typeof TerminalRoute
  '/wagers/$wagerId': typeof WagersWagerIdRoute
  '/wagers/new': typeof WagersNewRoute
  '/wagers': typeof WagersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/terminal': typeof TerminalRoute
  '/wagers/$wagerId': typeof WagersWagerIdRoute
  '/wagers/new': typeof WagersNewRoute
  '/wagers/': typeof WagersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/terminal'
    | '/wagers/$wagerId'
    | '/wagers/new'
    | '/wagers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/terminal'
    | '/wagers/$wagerId'
    | '/wagers/new'
    | '/wagers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/terminal'
    | '/wagers/$wagerId'
    | '/wagers/new'
    | '/wagers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TerminalRoute: typeof TerminalRoute
  WagersWagerIdRoute: typeof WagersWagerIdRoute
  WagersNewRoute: typeof WagersNewRoute
  WagersIndexRoute: typeof WagersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagers/': {
      id: '/wagers/'
      path: '/wagers'
      fullPath: '/wagers/'
      preLoaderRoute: typeof WagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagers/new': {
      id: '/wagers/new'
      path: '/wagers/new'
      fullPath: '/wagers/new'
      preLoaderRoute: typeof WagersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagers/$wagerId': {
      id: '/wagers/$wagerId'
      path: '/wagers/$wagerId'
      fullPath: '/wagers/$wagerId'
      preLoaderRoute: typeof WagersWagerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TerminalRoute: TerminalRoute,
  WagersWagerIdRoute: WagersWagerIdRoute,
  WagersNewRoute: WagersNewRoute,
  WagersIndexRoute: WagersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
