/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WagersIndexRouteImport } from './routes/wagers/index'
import { Route as WagersWagerIdRouteImport } from './routes/wagers/$wagerId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WagersIndexRoute = WagersIndexRouteImport.update({
  id: '/wagers/',
  path: '/wagers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WagersWagerIdRoute = WagersWagerIdRouteImport.update({
  id: '/wagers/$wagerId',
  path: '/wagers/$wagerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/wagers/$wagerId': typeof WagersWagerIdRoute
  '/wagers/': typeof WagersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/wagers/$wagerId': typeof WagersWagerIdRoute
  '/wagers': typeof WagersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminal': typeof TerminalRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wallet': typeof WalletRoute
  '/wagers/$wagerId': typeof WagersWagerIdRoute
  '/wagers/': typeof WagersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terminal'
    | '/verify-email'
    | '/wallet'
    | '/wagers/$wagerId'
    | '/wagers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terminal'
    | '/verify-email'
    | '/wallet'
    | '/wagers/$wagerId'
    | '/wagers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/terminal'
    | '/verify-email'
    | '/wallet'
    | '/wagers/$wagerId'
    | '/wagers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminalRoute: typeof TerminalRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WalletRoute: typeof WalletRoute
  WagersWagerIdRoute: typeof WagersWagerIdRoute
  WagersIndexRoute: typeof WagersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagers/': {
      id: '/wagers/'
      path: '/wagers'
      fullPath: '/wagers/'
      preLoaderRoute: typeof WagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wagers/$wagerId': {
      id: '/wagers/$wagerId'
      path: '/wagers/$wagerId'
      fullPath: '/wagers/$wagerId'
      preLoaderRoute: typeof WagersWagerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminalRoute: TerminalRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WalletRoute: WalletRoute,
  WagersWagerIdRoute: WagersWagerIdRoute,
  WagersIndexRoute: WagersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
