workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - test
  - build
  - deploy

.node-job:
  tags:
    - shared-fi
  image:
    name: node:22-bookworm-slim
    pull_policy: if-not-present
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - node --version
    - npm --version
    - npm ci --prefer-offline

verify:
  extends: .node-job
  stage: test
  script:
    - npm run lint:local
    - npm run test:local

build:
  extends: .node-job
  stage: build
  script:
    - npm run generate:local
    - npm run build:local
  artifacts:
    paths:
      - client/dist/
      - dist/
      - client/src/api/gen/
      - client/src/routeTree.gen.ts
    expire_in: 1 week

integration-tests:
  extends: .node-job
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "TODO"

e2e-tests:
  extends: .node-job
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "TODO"

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "TODO"