workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

variables:
  DOCKER_HOST: unix:///runner/services/docker/docker.sock
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"

.docker-job:
  image: docker:27-cli
  services:
    - name: docker:27-dind-rootless
  tags:
    - shared-fi
  before_script:
    - docker version
    - docker compose version
    - docker build -t pb138-project-dev -f Dockerfile.dev .

stages:
  - test
  - build
  - deploy

verify:
  extends: .docker-job
  stage: test
  script:
    - docker compose --profile tools run --rm app npm run lint:local
    - docker compose --profile tools run --rm app npm run test:local
  after_script:
    - docker compose down --remove-orphans || true

build:
  extends: .docker-job
  stage: build
  script:
    - docker compose --profile tools run --rm app npm run generate:local
    - docker compose --profile tools run --rm app npm run build:local
  artifacts:
    paths:
      - dist/
      - client/src/api/gen/
      - client/src/routeTree.gen.ts
    expire_in: 10 minutes
  after_script:
    - docker compose down --remove-orphans || true

integration-tests:
  stage: test
  tags:
    - shared-fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "TODO"

e2e-tests:
  stage: test
  tags:
    - shared-fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "TODO"

deploy:
  stage: deploy
  tags:
    - shared-fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "TODO"