workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

variables:
  DOCKER_HOST: unix:///runner/services/docker/docker.sock
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"

.docker-job:
  image: docker:27-cli
  services:
    - name: docker:27-dind-rootless
  tags:
    - shared-fi
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: "1"
    COMPOSE_DOCKER_CLI_BUILD: "1"
    DOCKER_DRIVER: overlay2
    NODE_BASE_IMAGE: "$CI_REGISTRY_IMAGE/base/node:22-bookworm-slim"
  before_script:
    - docker version
    - docker compose version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE/dev:cache" || true
    - docker build
        --cache-from "$CI_REGISTRY_IMAGE/dev:cache"
        --build-arg BUILDKIT_INLINE_CACHE=1
        --build-arg NODE_BASE_IMAGE="$NODE_BASE_IMAGE"
        -t pb138-project-dev
        -t "$CI_REGISTRY_IMAGE/dev:cache"
        -f Dockerfile.dev .
    - docker push "$CI_REGISTRY_IMAGE/dev:cache"

stages:
  - prepare
  - test
  - build
  - deploy

mirror-node-base:
  stage: prepare
  rules:
    - when: manual
  before_script:
    - docker version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull node:22-bookworm-slim
    - docker tag node:22-bookworm-slim "$CI_REGISTRY_IMAGE/base/node:22-bookworm-slim"
    - docker push "$CI_REGISTRY_IMAGE/base/node:22-bookworm-slim"

verify:
  extends: .docker-job
  stage: test
  script:
    - docker compose --profile tools run --rm app npm run lint:local
    - docker compose --profile tools run --rm app npm run test:local
  after_script:
    - docker compose down --remove-orphans || true

build:
  extends: .docker-job
  stage: build
  script:
    - docker compose --profile tools run --rm app npm run generate:local
    - docker compose --profile tools run --rm app npm run build:local
  artifacts:
    paths:
      - dist/
      - client/src/api/gen/
      - client/src/routeTree.gen.ts
    expire_in: 10 minutes
  after_script:
    - docker compose down --remove-orphans || true

integration-tests:
  stage: test
  tags:
    - shared-fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "TODO"

e2e-tests:
  stage: test
  tags:
    - shared-fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "TODO"

deploy:
  stage: deploy
  tags:
    - shared-fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "TODO"